MPIDE_DIR       = /opt/mpide-0022-linux32-20110822

TARGET          = blink

#BOARD_TAG      = mega_pic32_dbg
BOARD_TAG       = mega_pic32

ARDUINO_LIBS    = Wire \
                  Wire/utility

ARDUINO_PORT    = /dev/ttyUSB*

include chipKIT.mk
