
CXX             = g++ -std=c++17
CXXFLAGS        = $(shell pkg-config --cflags mozjs-128)
LDFLAGS         = $(shell pkg-config --libs mozjs-128 mozjs-128)

all:            factorial

#factorial:      factorial.cpp
