# Mac OS X
LIBGRF  = libgrafor.a
F77     = gfortran
CFLAGS  = -O
FFLAGS  = -O
LDFLAGS =
LIBS    =
#INSLIB  = /usr/greenhills/BIN/386/lib

# 386/ix with Green Hills Fortran
#LIBGRF  = libgrafor.a
#F77     = gf77
#CFLAGS  = -O
#FFLAGS  = -OM
#LDFLAGS =
#LIBS    =
#INSLIB  = /usr/greenhills/BIN/386/lib

# Vax under Ultrix
#LIBGRF  = libgrafor.a
#F77     = f77
#CFLAGS  = -O
#FFLAGS  = -O
#LDFLAGS =
#LIBS    =
#INSLIB  = /usr/lib

# Convex under BSD 4.3
#LIBGRF  = libgrafor.a
#F77     = fc
#CFLAGS  = -O
#FFLAGS  = -O2
#LDFLAGS =
#LIBS    =
#INSLIB  = /lib

# Xenix with Microsoft Fortran 286
#LIBGRF  = Llibgrafor.a
#F77     = cl
#CFLAGS  = -O -DMSF -Ml -Me -M2
#FFLAGS  = -Ox -FPi
#LDFLAGS = -Ml -i -M2
#LIBS    = -lccgi
#INSLIB  = /lib

OBJS  = addlev.o angler.o angrid.o appoly.o arc.o arc1.o arcang.o arcc1.o\
	arcela.o arcelb.o arcia.o arcib.o arcic.o arcid.o arcocc.o arcolc.o\
	arcoll.o areb1.o arrinl.o arrow.o astep.o atdx.o atdx1.o atdx2.o\
	atdx3.o atdy.o atdy1.o atdy2.o atdy3.o atran2.o atrst.o axes.o\
	axisc.o axonom.o bar.o bars.o beglev.o bita.o blan.o blanc.o blanch.o\
	bound.o box.o brline.o broken.o brolin.o bufl.o bypass.o cabin.o\
	ccntl.o ccntrp.o cell.o chensp.o cilind.o circ.o circle.o cirtac.o\
	cirtal.o cmgrid.o cmlc.o cms.o cncpp.o cnctcc.o cnctcl.o cnctcp.o\
	cnctll.o cnctlp.o cntlll.o condek.o coord.o coordt.o cornl.o cosin1.o\
	cosin2.o cppp.o cpr.o cross.o crossp.o ctccp.o ctcpp.o ctlll.o ctllp.o\
	ctlpp.o cubpol.o cxyr.o danppc.o dashp.o ddist.o deriv5.o diman.o\
	dimdro.o dimen.o dimet.o dist.o dracon.o dralim.o drawel.o drawte.o\
	drfram.o drw.o drwhl.o elips.o elps.o endlev.o endpg.o exmima.o\
	extln.o extrem.o exude.o fan1.o fan2.o fatarc.o fatlin.o fnroot.o\
	forfit.o forif.o forit.o full.o gffals.o grafer.o grid.o hallne.o\
	haloed.o hcind.o hcinit.o hcinv.o hcline.o hcmult.o hcncor.o hcncrd.o\
	hcprsp.o hcrot1.o hcsurf.o hcunit.o histgm.o hldln.o ilimtn.o inches.o\
	inclin.o init.o insdek.o inside.o intrsc.o isolin.o isomet.o italic.o\
	itplbv.o ivest.o izflin.o izlin.o izolin.o keypo.o lcross.o lesq.o\
	letizo.o letspl.o levfun.o levmap.o lgline.o licon.o limits.o\
	linemc.o linemo.o lineo.o linfil.o linint.o linnum.o lint.o litan.o\
	lmll.o locext.o look.o lower.o lpal.o lparld.o lparlp.o lparx.o\
	lpary.o lpax.o lperlp.o lpp.o lscale.o lsfit.o map.o markbe.o\
	marker.o matevl.o minmax.o mms.o mnmx.o modgf.o mova.o movb.o\
	movc.o move.o move1.o move2.o move3.o mtmpl.o mxmult.o narrow.o\
	newfrm.o nextrg.o notch.o notch1.o number.o numlin.o oper.o pac.o\
	page.o paint.o pata.o patc.o patch.o patl.o pcdp.o pcnap.o pcnitc.o\
	pcnp.o pcntrc.o pen.o picc.o pictur.o piepp.o pilc.o pill.o piss.o\
	pldp.o plnp.o pmidpp.o pmlp.o pmp.o pmpp.o pnordr.o polg.o poline.o\
	polreg.o polyg.o prap.o prep.o prj.o prjhl.o projct.o prsp.o pscale.o\
	ptlcc.o ptlpc.o pval.o pvpl.o pxy.o quadra.o raise.o raxes.o rccntc.o\
	rdaca.o rdacb.o rdacc.o rdacd.o rdaea.o rdaeb.o rdcrc.o rdelp.o\
	rdmva.o rdmvb.o rdmvc.o rdmve.o rdstr.o reblan.o rect.o recur.o\
	region.o rentch.o renum.o reset.o rotate.o roth.o savetr.o scren1.o\
	scren2.o scrmod.o sdpg.o search.o secant.o see.o see1.o segang.o\
	set.o setbe.o setra.o settr.o sfcfit.o shade.o shdown.o shear.o\
	shift.o shup.o signa.o sincl.o sizlin.o siznum.o slinst.o sminv.o\
	smtbvf.o smtone.o smtsim.o sort3.o sortc.o sortcn.o sortl.o sortp.o\
	sortpt.o sorty.o spherg.o spherv.o spiral.o spline.o splint.o\
	splitp.o spnp.o star.o storin.o strmod.o strot3.o suplin.o svlseg.o\
	symbol.o tcalc.o tdaxes.o tdlim.o tdliml.o tdline.o tdmp.o tdrot.o\
	tdscal.o tdsect.o tdtran.o testvs.o tfm.o thaxes.o threed.o tmf.o\
	tmlgf.o token.o tpf.o tranh.o transf.o transl.o trdraw.o trg.o\
	trgrid.o tridig.o trig.o trigl.o tringl.o trsurf.o view.o vplim.o\
	where.o wherp.o wraca.o wracb.o wracc.o wracd.o wraea.o wraeb.o\
	wrcrc.o wrelp.o wrmva.o wrmvb.o wrmvc.o wrmve.o wrstr.o xaxis.o\
	xiliy.o xiliy1.o xlgax.o xpol.o xysort.o yaxis.o ylgax.o ypol.o\
	zapit.o zint.o

all:    $(OBJS)
	-rm -f ../libgrafor.a
	ar r ../libgrafor.a $(OBJS)

ag:;    make compag
ho:;    make compho
ps:;    make compps
tz:;    make comptz

compag: [a-g]*.o
compho: [h-o]*.o
compps: [p-s]*.o
comptz: [t-z]*.o

recompile:
	$(F77) -c $(FFLAGS) *.f

clean:
	rm -f *~ *.o

.f.o:
	$(F77) -c $(FFLAGS) $<

.SUFFIXES: .o .c .f .s .out
