CFLAGS          = -O -g
LDFLAGS         = -Wl,-rpath,/usr/local/lib -lSDL_bgi -lSDL2_image -lSDL2
PROG            = particles xorlines hopalong kaleido sdlbgidemo

all:            $(PROG)

clean:
		rm -rf *.o $(PROG) *.dSYM
