CXX         = c++ -std=c++17
CXXFLAGS    = -I /opt/homebrew/include -Wall -O
LDFLAGS     = -L /opt/homebrew/lib -lgmpxx -lgmp

all:    fibonacci factorial n-times

clean:
	rm -f fibonacci factorial n-times
