INSTDIR		= /usr/local

all:

clean:
		rm -f *.tmp *.o *~

install:
		install -d $(INSTDIR)/lib/pic16/include
		install -c pic12c5xx.h $(INSTDIR)/lib/pic16/include
		install -c pic12c5xx.inc $(INSTDIR)/lib/pic16/include
