; Generated by c86 (as86) 5.2.0 (dev) from hello.i
	USE16	86
	.data
.L1:
	.ascii	"Hello XT!"
	.byte	0xa,0x0
	.text
	.align	2
	.global	_main
_main:
	; Line	4, {
	push	bp
	mov	bp, sp
	; Line	5,     printf("Hello XT!\n");
	mov	ax, #.L1
	push	ax
	call	_printf
	mov	sp, bp
	pop	bp
	ret
	.extern	_printf
	.data
