#!/usr/bin/env python3
#
# Show octal word of besm6 in ISO encoding.
#
import sys

if len(sys.argv) != 2:
    print("Usage: iso number")
    sys.exit(1)

value = int(sys.argv[1], 8)
print("%#o" % value)

text = ''
for shift in range(40, -1, -8):
    byte = (value >> shift) & 0xff
    print(f" {byte:03o}", end='')
    text += chr(byte)
print()
print(text)
