.TH LOTO 6
.SH ИМЯ
loto \- игра в лото, аналогичная имеющейся в системе "Джин" на ЭВМ БЭСМ-6.
.SH ФОРМАТ
/usr/games/loto
.SH ОПИСАНИЕ
.TP 20
Цель игры.
Цель игры - первым набрать 1100 очков. Каждый участник должен
задать "имя", под которым он будет участвовать в игре. Пустая посылка
прерывает ввод имен.
.TP
Прохождение игры.
Игра состоит из этапов. Этап - это период, когда играет один
из участников. На каждом этапе участник располагает 5-ю кубиками, на
которые могут выпасть значения от 1 до 6.
В зачет идут выпавшие 1, 5, а также комбинации из 3-х, 4-х и
5-ти одинаковых значений. Кубик с зачетным значением на следующем
шаге этапа в игре не участвует. При выпадении зачетных значений на
всех счетчиках игроку предоставляется "призовая игра".
.TP
Подсчет очков.
Очки подсчитываются следующим образом: 1-ца считается за 10
очков; 5-ка - за 5 очков; комбинация из 3-х одинаковых цифр - (N*10);
из 4-х - (N*20); из 5-ти - (N*40), где N={1(10),2,3,4,5,6}.
Накопление очков продолжается, пока на запрос "Продолжать?" не будет
дан отрицательный ответ. При отсутствии зачетных значений на текущем
шаге вся накопленная за этап сумма пропадает.
.TP
Обгоны.
При обгоне одним участником других у последних списывается
по 50 очков, а данному игроку добавляется по 50 очков с каждого.
Обгоны начинают учитываться, если игрок хотя бы раз набрал некоторое
количество очков.
.TP
Рубежи.
Рубежами называются интервалы с 400 по 499 и с 900 по 999
очков. Преодолеть рубеж необходимо за один этап. При неудаче у
игрока списывается 100 очков. Если же при попытке набрать требуемую
сумму у игрока пропадают очки, то списания не производится. Заходить
за нижнюю границу рубежей разрешается.
.TP
Запросы.
На вопрос "Продолжать?" нужно отвечать "y", "n", "д" или
"н". Пустая посылка равносильна "д". При задании "р" происходит
подсчет результатов. По команде "к" игра прерывается.
.PP
.SH ФАЙЛЫ
/usr/games/loto
