/*
 * Copyright (C) 2005 Serge Vakulenko, <vak@cronyx.ru>
 *
 * This file is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can redistribute this file and/or modify it under the terms of the GNU
 * General Public License (GPL) as published by the Free Software Foundation;
 * either version 2 of the License, or (at your discretion) any later version.
 * See the accompanying file "COPYING" for more details.
 */
#define ROW(a,b,c,d,e,f,g) (a | b<<1 | c<<2 | d<<3 | e<<4 | f<<5 | g<<6)
#define _ 0
#define O 1

/*
 * Фразы.
 */
static unsigned char pic_cronyx [] __attribute__ ((progmem)) = {
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,_,_,_,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,O,_,_,O),
	ROW (_,_,O,O,_,_,O),
	ROW (_,O,_,O,_,_,O),
	ROW (O,_,_,_,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,O,O,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,O,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,O,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,O,O),
	ROW (_,_,_,O,O,_,_),
	ROW (O,O,O,_,_,_,_),
	ROW (_,_,_,O,O,_,_),
	ROW (_,_,_,_,_,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,_,_,_,O,O),
	ROW (_,_,O,_,O,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,O,_,O,_,_),
	ROW (O,O,_,_,_,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,O,_,O,_,_),
	ROW (_,O,_,_,_,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,O,_,_,_,O),
	ROW (_,_,O,_,_,_,O),
	ROW (_,_,O,_,_,_,O),
	ROW (_,_,_,O,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,O,O,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,O,_,_,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,_,_,O,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,O,_,O,_,_),
	ROW (_,O,_,_,_,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,_,_,_,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),

	0xff
};

static unsigned char pic_newyear [] __attribute__ ((progmem)) = {
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,_,_,_,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (_,_,_,O,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,O,O,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (O,_,_,O,_,_,O),
	ROW (O,_,_,O,_,_,O),
	ROW (O,_,_,O,_,_,O),
	ROW (_,O,O,_,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (O,_,_,O,_,_,_),
	ROW (_,O,O,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,O,_),
	ROW (_,_,_,_,O,_,_),
	ROW (_,_,_,_,_,O,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,O),
	ROW (_,_,_,_,_,_,O),
	ROW (_,_,_,_,_,_,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,O,O,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (_,O,_,_,_,_,O),
	ROW (_,O,_,_,_,_,O),
	ROW (_,O,O,O,O,O,O),
	ROW (O,O,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,O,O,O,O,O,_),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (O,_,_,_,_,_,O),
	ROW (_,O,O,O,O,O,_),
	ROW (_,_,_,_,_,_,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,O,_),
	ROW (_,_,_,_,O,_,_),
	ROW (_,_,_,_,_,O,_),
	ROW (O,O,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (O,_,O,O,O,O,O),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),
	ROW (_,_,_,_,_,_,_),

	0xff
};

const unsigned char *pic_table [] = {
	pic_cronyx,
	pic_newyear,
	0,
};
