#!/usr/local/bin/perl
eval "exec /usr/local/bin/perl -S $0 $*"
	if $running_under_some_shell;

$pat = 'S n C4 x8';
$inet = 2;
$echo = 7;
$smtp = 25;
$nntp = 119;
$test = 2345;

$SIG{'INT'} = 'dokill';

$this = pack($pat,$inet,0,    192,124,180,1);
$that = pack($pat,$inet,$nntp,192,124,180,2);

if (socket(S,2,1,6)) { print "socket ok\n"; } else { die $!; }
if (bind(S,$this)) { print "bind ok\n"; } else { die $!; }
if (connect(S,$that)) { print "connect ok\n"; } else { die $!; }

select(S); $| = 1; select(stdout);

if ($child = fork) {
    while (<STDIN>) {
	print S;
    }
    sleep 3;
    do dokill();
}
else {
    while (<S>) {
	print;
    }
}

sub dokill { kill 9,$child if $child; }
