#!/usr/local/bin/python
#
# CGI script for playing Mpeg-3 files over Internet.
# Usage:
#	play ? v=arg1 & v=arg2 & ... [ & random=yes ]
# The arguments are the file and directory names, relative
# to the base directory name BASEDIR.
# The script prints the m3u playlist, consisting of the single
# line - the URL to the mpeg3 script with all needed arguments.
#

import sys, os, time, cgi

HOME = "http://hanoi.cronyx.ru"
PLAYER = "/exec/mpeg3"
sys.stderr = sys.stdout

if not os.environ.has_key("REQUEST_METHOD"):
	# Test mode
	os.environ["QUERY_STRING"] = "v=test&random=yes"

form = cgi.FormContentDict()
if not form.has_key("v"):
	print "Status: 503 Internal error"
	print "Content-type: text/html"
	print
	print '<h1> Internal CGI script error </h1>'
	print 'No form field "v"'
	sys.exit (0)

list = form["v"]
if list == "":
	print "Status: 503 Internal error"
	print "Content-type: text/html"
	print
	print '<h1> Internal CGI script error </h1>'
	print 'Empty form field "v"'
	sys.exit (0)

argv = ""
for item in list:
	argv = argv + "&" + item

if form.has_key("random") and form["random"] == ["yes"]:
	argv = argv + "&-random"

i = 0
while 1:
	i = i+1
	filename = "/tmp/play" + `i` + ".m3u"
	realname = "/www" + filename
	try:
		# Find the file older than 20 min
		st = os.stat (realname)
		if st[8] + 20*60 < time.time():
			break
	except:
		break

file = open (realname, 'w')
file.write (HOME + PLAYER + "?" + argv[1:] + "\r\n")
file.close()

print "Status: 302 Moved"
print "Location: " + HOME + filename
print
print "Enjoy!"

sys.exit (0)
