#!/bin/sh

if [[ $# -ne 1 ]]; then
    echo "Usage: pico-prog <file>"
else
    file="$1"
    openocd -f interface/picoprobe.cfg \
            -f target/rp2040.cfg \
            -c "program $file verify reset exit"
fi
