INSTDIR	= /usr/local

all:

clean:
	rm -f *.tmp *.o *~

install:
	install -d $(INSTDIR)/lib/pic17/include
	install -c pic17c43.h $(INSTDIR)/lib/pic17/include
	install -c pic17c43.inc $(INSTDIR)/lib/pic17/include
